import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Homes from "../components/Home/Home";
import Loading from "../components/Loading/Loading";
const Home: NextPage = () => {
  const [LoadingPage, setLoadingPage] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      setLoadingPage(false);
    }, 5200);
  }, []);
  return (
    <div>
      {LoadingPage ? (
        <Loading />
      ) : (
        <div>
          <Head>
            <title>{`We help you find solutions through design`}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link
              rel="apple-touch-icon"
              sizes="76x76"
              href="/apple-touch-icon.png"
            />
            <link
              rel="icon"
              type="image/png"
              sizes="32x32"
              href="/favicon-32x32.png"
            />
            <link
              rel="icon"
              type="image/png"
              sizes="16x16"
              href="/favicon-16x16.png"
            />
            <link rel="manifest" href="/site.webmanifest" />
            <link
              rel="mask-icon"
              href="/safari-pinned-tab.svg"
              color="#5bbad5"
            />
            <meta name="msapplication-TileColor" content="#da532c" />
            <meta name="theme-color" content="#ffffff"></meta>
          </Head>
          <Homes />
        </div>
      )}
      {/* <Modal /> */}
    </div>
  );
};

export default Home;
